services:
  services-database:
    image: postgres:17.4
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: public
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d public" ]
      interval: 5s
      timeout: 30s
    ports:
      - "5432:5432"