sources:
  - name: users-service
    handler:
      graphql:
        endpoint: http://localhost:8080/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: classes-service
    handler:
      graphql:
        endpoint: http://localhost:8081/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: grades-service
    handler:
      graphql:
        endpoint: http://localhost:8082/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"