serve:
  fork: 1
  hostname: 0.0.0.0
sources:
  - name: users-service
    handler:
      graphql:
        endpoint: http://{env.USERS_SERVICE_HOST:localhost}:8080/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: classes-service
    handler:
      graphql:
        endpoint: http://{env.CLASSES_SERVICE_HOST:localhost}:8081/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: grades-service
    handler:
      graphql:
        endpoint: http://{env.GRADES_SERVICE_HOST:localhost}:8082/graphql
        operationHeaders:
          Authorization: "{context.headers.authorization}"